import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(__dirname, "..", "..");
const routes: string[] = JSON.parse(readFileSync(join(ROOT, "scripts", "pwa-routes.json"), "utf8"));

/** Every app route as a URL path; [language] is expanded to its static params (zh / en). */
function appRoutes(dir = join(ROOT, "app")): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...appRoutes(full));
    else if (entry === "page.tsx") {
      const path = "/" + relative(join(ROOT, "app"), dir).split(sep).join("/");
      found.push(path === "/" ? "/" : path);
    }
  }
  return found.flatMap((p) => (p.includes("[language]") ? ["zh", "en"].map((l) => p.replace("[language]", l)) : [p]));
}

describe("service worker precache list", () => {
  it("covers every page so the whole app works offline", () => {
    // "/" only redirects to /dashboard, which is precached.
    expect(appRoutes().filter((p) => p !== "/").sort()).toEqual([...routes].sort());
  });

  it("has no dynamic segments (they can't be prerendered for offline use)", () => {
    expect(appRoutes().filter((p) => p.includes("["))).toEqual([]);
  });

  it("template has every placeholder the build script fills in", () => {
    const template = readFileSync(join(ROOT, "scripts", "sw.template.js"), "utf8");
    for (const placeholder of ["__VERSION__", "__BASE__", "__ROUTES__", "__STATIC_FILES__"]) expect(template).toContain(placeholder);
    expect(existsSync(join(ROOT, "public", "manifest.webmanifest"))).toBe(false); // generated by app/manifest.ts
  });
});
